using System.Collections.Immutable;
using Confast.Web.Features.Identity;

namespace Confast.Web.Features.Authorization;

public static class AuthorizationSeeds
{
    public static ImmutableArray<string> ReadOnly { get; } =
    [
        Permissions.Customers.Read,
        Permissions.Plants.Read,
        Permissions.PlantCertificationRecipients.Read,
        Permissions.PlantCertificationSettings.Read,
        Permissions.Parts.Read,
        Permissions.Gages.Read,
        Permissions.GageTypes.Read,
        Permissions.InspectionCriteria.Read,
        Permissions.MasterPrints.Read,
        Permissions.Inspections.Read,
        Permissions.Certifications.Read,
        Permissions.Suppliers.Read,
        Permissions.Shipments.Read,
        Permissions.Containers.Read,
        Permissions.BillsOfLading.Read,
        Permissions.ProductionSchedules.Read,
    ];

    public static ImmutableArray<string> Quality { get; } =
    [
        Permissions.Customers.Create,
        Permissions.Customers.Update,
        Permissions.Plants.Create,
        Permissions.Plants.Update,
        Permissions.PlantCertificationRecipients.Create,
        Permissions.PlantCertificationRecipients.Update,
        Permissions.PlantCertificationRecipients.Delete,
        Permissions.PlantCertificationSettings.Update,
        Permissions.Parts.Create,
        Permissions.Parts.Update,
        Permissions.Gages.Create,
        Permissions.Gages.Update,
        Permissions.GageTypes.Create,
        Permissions.GageTypes.Update,
        Permissions.InspectionCriteria.Create,
        Permissions.InspectionCriteria.Update,
        Permissions.InspectionCriteria.Delete,
        Permissions.InspectionCriteria.Publish,
        Permissions.MasterPrints.Update,
        Permissions.MasterPrints.Delete,
        Permissions.Inspections.Create,
        Permissions.Inspections.Update,
        Permissions.Inspections.Duplicate,
        Permissions.Inspections.Flip,
        Permissions.Inspections.TransferQuantity,
        Permissions.Inspections.ApproveDeviation,
        Permissions.InspectionSheets.Export,
        Permissions.Certifications.Create,
        Permissions.Certifications.Delete,
        Permissions.Certifications.BuildPackage,
        Permissions.Certifications.SendEmail,
        Permissions.Suppliers.Create,
        Permissions.Suppliers.Update,
        Permissions.Shipments.Create,
        Permissions.Shipments.Update,
        Permissions.Shipments.Delete,
        Permissions.Containers.Create,
        Permissions.Containers.Update,
        Permissions.Containers.Delete,
        Permissions.ContainerContents.Update,
        Permissions.BillsOfLading.Create,
        Permissions.BillsOfLading.Update,
        Permissions.Containers.Receive,
        Permissions.Containers.CorrectReceipt,
        Permissions.Containers.Unreceive,
        Permissions.Containers.CorrectReceivedQuantities,
        Permissions.Receiving.Read,
        Permissions.Receiving.BeginInspection,
        Permissions.Receiving.BumpQuantity,
        Permissions.Receiving.ReverseAllocation,
        Permissions.Chat.Access,
        Permissions.Chat.CreateConversations,
        Permissions.Chat.SendMessages,
        Permissions.Chat.ScheduleMessages,
        Permissions.Chat.CreateThreads,
        Permissions.Chat.CreatePolls,
        Permissions.Chat.VotePolls,
        Permissions.Chat.React,
        Permissions.Chat.PinMessages,
        Permissions.Chat.EditOwnMessages,
        Permissions.Chat.DeleteOwnMessages,
        Permissions.Chat.CreateChannels,
        Permissions.Chat.UpdateChannels,
        Permissions.Chat.DeleteChannels,
        Permissions.Chat.ManagePrivateChannelMembers,
        Permissions.Chat.CreateCategories,
        Permissions.Chat.ManageCategories,
        Permissions.Chat.ReorderChannels,
        Permissions.Chat.ManageGroupConversations,
    ];

    public static ImmutableArray<string> Production { get; } =
    [
        Permissions.Customers.Create,
        Permissions.Customers.Update,
        Permissions.Plants.Create,
        Permissions.Plants.Update,
        Permissions.Parts.Create,
        Permissions.Parts.Update,
        Permissions.Suppliers.Create,
        Permissions.Suppliers.Update,
        Permissions.Shipments.Create,
        Permissions.Shipments.Update,
        Permissions.Shipments.Delete,
        Permissions.Containers.Create,
        Permissions.Containers.Update,
        Permissions.Containers.Delete,
        Permissions.ContainerContents.Update,
        Permissions.BillsOfLading.Create,
        Permissions.BillsOfLading.Update,
        Permissions.Containers.Receive,
        Permissions.Containers.CorrectReceipt,
        Permissions.Containers.Unreceive,
        Permissions.Containers.CorrectReceivedQuantities,
        Permissions.ProductionJobs.Create,
        Permissions.ProductionJobs.Update,
        Permissions.ProductionJobs.Delete,
        Permissions.MachineDowntime.Create,
        Permissions.MachineDowntime.Update,
        Permissions.MachineDowntime.Delete,
        Permissions.ProductionSchedules.Arrange,
        Permissions.ProductionSchedules.Optimize,
        Permissions.ProductionSchedules.AppendContainerPart,
        Permissions.ProductionSchedules.StartWork,
        Permissions.ProductionSchedules.RecordProgress,
        Permissions.ProductionSchedules.CompleteWork,
        Permissions.ProductionSchedules.CorrectProgress,
        Permissions.ProductionLogs.Read,
        Permissions.ProductionLogs.Create,
        Permissions.ProductionLogs.Update,
        Permissions.ProductionLogs.StartRun,
        Permissions.ProductionLogs.StopRun,
        Permissions.ProductionLogs.ResumeRun,
        Permissions.ProductionLogs.CorrectLine,
        Permissions.ProductionReports.Read,
        Permissions.Chat.Access,
        Permissions.Chat.CreateConversations,
        Permissions.Chat.SendMessages,
        Permissions.Chat.ScheduleMessages,
        Permissions.Chat.CreateThreads,
        Permissions.Chat.CreatePolls,
        Permissions.Chat.VotePolls,
        Permissions.Chat.React,
        Permissions.Chat.PinMessages,
        Permissions.Chat.EditOwnMessages,
        Permissions.Chat.DeleteOwnMessages,
        Permissions.Chat.CreateChannels,
        Permissions.Chat.UpdateChannels,
        Permissions.Chat.DeleteChannels,
        Permissions.Chat.ManagePrivateChannelMembers,
        Permissions.Chat.CreateCategories,
        Permissions.Chat.ManageCategories,
        Permissions.Chat.ReorderChannels,
        Permissions.Chat.ManageGroupConversations,
    ];

    public static ImmutableArray<string> Administrator { get; } =
    [
        Permissions.Users.Read,
        Permissions.Users.Create,
        Permissions.Users.Update,
        Permissions.Users.Delete,
        Permissions.Users.ManageRoles,
        Permissions.Users.ResetPasswords,
        Permissions.Plants.Delete,
        Permissions.Parts.Delete,
        Permissions.PartFlipDefinitions.Read,
        Permissions.PartFlipDefinitions.Create,
        Permissions.PartFlipDefinitions.Update,
        Permissions.PartFlipDefinitions.Delete,
        Permissions.Inspections.Delete,
        Permissions.Inspections.UndoLineage,
        Permissions.Certifications.TemporarilyCompletePackage,
        Permissions.CertificationEmailTemplates.Read,
        Permissions.CertificationEmailTemplates.Update,
        Permissions.CertificationEmailSettings.Read,
        Permissions.CertificationEmailSettings.Update,
        Permissions.NominalToleranceSettings.Read,
        Permissions.NominalToleranceSettings.Update,
        Permissions.Development.SetBusinessDate,
        Permissions.Development.SendTestEmail,
        Permissions.Containers.CorrectDepartedMetadata,
        Permissions.Containers.DeleteDeparted,
        Permissions.BillsOfLading.CorrectDeparted,
        Permissions.SortingMachines.Read,
        Permissions.SortingMachines.Create,
        Permissions.SortingMachines.Update,
        Permissions.PartMachineEligibility.Read,
        Permissions.PartMachineEligibility.Create,
        Permissions.PartMachineEligibility.Update,
        Permissions.PartMachineEligibility.Delete,
        Permissions.ProductionCalendars.Read,
        Permissions.ProductionCalendars.Update,
        Permissions.ProductionHolidays.Read,
        Permissions.ProductionHolidays.Create,
        Permissions.ProductionHolidays.Update,
        Permissions.ProductionHolidays.Delete,
        Permissions.ProductionDowntimeReasons.Read,
        Permissions.ProductionDowntimeReasons.Create,
        Permissions.ProductionDowntimeReasons.Update,
        Permissions.ProductionDowntimeReasons.Delete,
        Permissions.ProductionSettings.Read,
        Permissions.ProductionSettings.Update,
        Permissions.SortLogDowntimeCauses.Read,
        Permissions.SortLogDowntimeCauses.Create,
        Permissions.SortLogDowntimeCauses.Update,
        Permissions.SortLogDowntimeCauses.Delete,
        Permissions.Chat.DeleteOthersMessages,
        Permissions.Chat.AdministerChannels,
        Permissions.Roles.Read,
        Permissions.Roles.Create,
        Permissions.Roles.Update,
        Permissions.Roles.Delete,
        Permissions.Roles.ManagePermissions,
        Permissions.Roles.ManageInheritance,
    ];

    public static IEnumerable<RolePermission> Grants =>
        ReadOnly.Select(x => new RolePermission { RoleId = AppRoles.ReadOnlyId, PermissionKey = x })
            .Concat(Quality.Select(x => new RolePermission { RoleId = AppRoles.QualityId, PermissionKey = x }))
            .Concat(Production.Select(x => new RolePermission { RoleId = AppRoles.ProductionId, PermissionKey = x }))
            .Concat(Administrator.Select(x => new RolePermission { RoleId = AppRoles.AdministratorId, PermissionKey = x }));

    public static RoleInheritance[] Edges =>
    [
        new() { ChildRoleId = AppRoles.AdministratorId, ParentRoleId = AppRoles.QualityId },
        new() { ChildRoleId = AppRoles.AdministratorId, ParentRoleId = AppRoles.ProductionId }
    ];
}
