// <auto-generated />
using System;
using Confast.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Confast.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260826132717_AddInspectionQuantityReceived")]
    partial class AddInspectionQuantityReceived
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Confast.Web.Features.Customers.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AddressLine1")
                        .HasColumnType("text")
                        .HasColumnName("address_line_1");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text")
                        .HasColumnName("address_line_2");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Confast.Web.Features.Gages.Gage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("GageNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gage_number");

                    b.Property<long>("GageTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("gage_type_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("PK_gages");

                    b.HasIndex("GageNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_gages_gage_number");

                    b.HasIndex("GageTypeId")
                        .HasDatabaseName("IX_gages_gage_type_id");

                    b.ToTable("gages", (string)null);
                });

            modelBuilder.Entity("Confast.Web.Features.Gages.GageType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("PK_gage_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_gage_types_name");

                    b.ToTable("gage_types", (string)null);
                });

            modelBuilder.Entity("Confast.Web.Features.InspectionCriteria.InspectionCriteriaRevision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ChangeNote")
                        .HasColumnType("text")
                        .HasColumnName("change_note");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<byte[]>("MasterPrintContent")
                        .HasColumnType("bytea")
                        .HasColumnName("master_print_content");

                    b.Property<string>("MasterPrintFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("master_print_file_name");

                    b.Property<DateTimeOffset?>("MasterPrintUploadedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("master_print_uploaded_at_utc");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PartDescription")
                        .HasColumnType("text")
                        .HasColumnName("part_description");

                    b.Property<long>("PartId")
                        .HasColumnType("bigint")
                        .HasColumnName("part_id");

                    b.Property<string>("PrintRevisionNumber")
                        .HasColumnType("text")
                        .HasColumnName("print_revision_number");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("revision_number");

                    b.Property<string>("SpecificationUsed")
                        .HasColumnType("text")
                        .HasColumnName("specification_used");

                    b.Property<DateTimeOffset?>("SupersededAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("superseded_at_utc");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("PK_inspection_criteria_revisions");

                    b.HasAlternateKey("Id", "PartId")
                        .HasName("AK_inspection_criteria_revisions_id_part_id");

                    b.HasIndex("PartId", "RevisionNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_inspection_criteria_revisions_part_id_revision_number");

                    b.HasIndex(new[] { "PartId" }, "IX_inspection_criteria_revisions_current_guard")
                        .IsUnique()
                        .HasDatabaseName("UX_inspection_criteria_revisions_one_current_per_part")
                        .HasFilter("published_at_utc IS NOT NULL AND superseded_at_utc IS NULL");

                    b.HasIndex(new[] { "PartId" }, "IX_inspection_criteria_revisions_draft_guard")
                        .IsUnique()
                        .HasDatabaseName("UX_inspection_criteria_revisions_one_draft_per_part")
                        .HasFilter("published_at_utc IS NULL");

                    b.ToTable("inspection_criteria_revisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_inspection_criteria_revisions_revision_number", "revision_number > 0");

                            t.HasCheckConstraint("CK_inspection_criteria_revisions_superseded_after_published", "superseded_at_utc IS NULL OR published_at_utc IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Confast.Web.Features.InspectionCriteria.InspectionCriterion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<long?>("GageTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("gage_type_id");

                    b.Property<long>("InspectionCriteriaRevisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("inspection_criteria_revision_id");

                    b.Property<string>("InspectionMethod")
                        .HasColumnType("text")
                        .HasColumnName("inspection_method");

                    b.Property<int>("InspectionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("inspection_number");

                    b.Property<string>("MaximumOrTolerance")
                        .HasColumnType("text")
                        .HasColumnName("maximum_or_tolerance");

                    b.Property<string>("Minimum")
                        .HasColumnType("text")
                        .HasColumnName("minimum");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("PK_inspection_criteria");

                    b.HasAlternateKey("Id", "InspectionCriteriaRevisionId")
                        .HasName("AK_inspection_criteria_id_revision_id");

                    b.HasIndex("GageTypeId")
                        .HasDatabaseName("IX_inspection_criteria_gage_type_id");

                    b.HasIndex("InspectionCriteriaRevisionId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("UX_inspection_criteria_revision_id_display_order");

                    b.HasIndex("InspectionCriteriaRevisionId", "InspectionNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_inspection_criteria_revision_id_inspection_number");

                    b.ToTable("inspection_criteria", null, t =>
                        {
                            t.HasCheckConstraint("CK_inspection_criteria_display_order", "display_order > 0");

                            t.HasCheckConstraint("CK_inspection_criteria_inspection_number", "inspection_number > 0");
                        });
                });

            modelBuilder.Entity("Confast.Web.Features.InspectionCriteria.SecondaryProcessRequirement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("InspectionCriteriaRevisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("inspection_criteria_revision_id");

                    b.Property<long>("SecondaryProcessTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("secondary_process_type_id");

                    b.Property<string>("Specification")
                        .HasColumnType("text")
                        .HasColumnName("specification");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("PK_secondary_process_requirements");

                    b.HasIndex("InspectionCriteriaRevisionId")
                        .HasDatabaseName("IX_secondary_process_requirements_revision_id");

                    b.HasIndex("SecondaryProcessTypeId")
                        .HasDatabaseName("IX_secondary_process_requirements_type_id");

                    b.ToTable("secondary_process_requirements", (string)null);
                });

            modelBuilder.Entity("Confast.Web.Features.InspectionCriteria.SecondaryProcessType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK_secondary_process_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_secondary_process_types_name");

                    b.ToTable("secondary_process_types", null, t =>
                        {
                            t.HasCheckConstraint("CK_secondary_process_types_name_not_blank", "btrim(name) <> ''");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Heat Treat"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Clean"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Patch"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Plate"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Sort"
                        });
                });

            modelBuilder.Entity("Confast.Web.Features.Inspections.Inspection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConformancePoNumber")
                        .HasColumnType("text")
                        .HasColumnName("conformance_po_number");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly?>("DateReceived")
                        .HasColumnType("date")
                        .HasColumnName("date_received");

                    b.Property<long>("InspectionCriteriaRevisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("inspection_criteria_revision_id");

                    b.Property<DateOnly>("InspectionDate")
                        .HasColumnType("date")
                        .HasColumnName("inspection_date");

                    b.Property<string>("Inspector")
                        .HasColumnType("text")
                        .HasColumnName("inspector");

                    b.Property<string>("LotNumber")
                        .HasColumnType("text")
                        .HasColumnName("lot_number");

                    b.Property<string>("ManufacturerLotNumber")
                        .HasColumnType("text")
                        .HasColumnName("manufacturer_lot_number");

                    b.Property<long>("PartId")
                        .HasColumnType("bigint")
                        .HasColumnName("part_id");

                    b.Property<int?>("QuantityInspected")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_inspected");

                    b.Property<int?>("QuantityReceived")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_received");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("PK_inspections");

                    b.HasAlternateKey("Id", "InspectionCriteriaRevisionId")
                        .HasName("AK_inspections_id_revision_id");

                    b.HasIndex("InspectionCriteriaRevisionId")
                        .HasDatabaseName("IX_inspections_revision_id");

                    b.HasIndex("InspectionDate")
                        .HasDatabaseName("IX_inspections_inspection_date");

                    b.HasIndex("PartId")
                        .HasDatabaseName("IX_inspections_part_id");

                    b.HasIndex("InspectionCriteriaRevisionId", "PartId");

                    b.ToTable("inspections", null, t =>
                        {
                            t.HasCheckConstraint("CK_inspections_quantity_inspected", "quantity_inspected IS NULL OR quantity_inspected > 0");

                            t.HasCheckConstraint("CK_inspections_quantity_received", "quantity_received IS NULL OR quantity_received > 0");
                        });
                });

            modelBuilder.Entity("Confast.Web.Features.Inspections.InspectionResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("ActualMax")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("actual_max");

                    b.Property<decimal?>("ActualMin")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("actual_min");

                    b.Property<long>("InspectionCriteriaRevisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("inspection_criteria_revision_id");

                    b.Property<long>("InspectionCriterionId")
                        .HasColumnType("bigint")
                        .HasColumnName("inspection_criterion_id");

                    b.Property<long>("InspectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("inspection_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("PK_inspection_results");

                    b.HasIndex("InspectionCriterionId", "InspectionCriteriaRevisionId")
                        .HasDatabaseName("IX_inspection_results_criterion_id_revision_id");

                    b.HasIndex("InspectionId", "InspectionCriteriaRevisionId");

                    b.HasIndex("InspectionId", "InspectionCriterionId")
                        .IsUnique()
                        .HasDatabaseName("UX_inspection_results_inspection_id_criterion_id");

                    b.ToTable("inspection_results", null, t =>
                        {
                            t.HasCheckConstraint("CK_inspection_results_actual_minimum_maximum", "actual_min IS NULL OR actual_max IS NULL OR actual_min <= actual_max");
                        });
                });

            modelBuilder.Entity("Confast.Web.Features.Parts.Part", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("part_number");

                    b.Property<string>("Revision")
                        .HasColumnType("text")
                        .HasColumnName("revision");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("PK_parts");

                    b.HasIndex("CustomerId", "PartNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_parts_customer_id_part_number");

                    b.ToTable("parts", (string)null);
                });

            modelBuilder.Entity("Confast.Web.Features.Gages.Gage", b =>
                {
                    b.HasOne("Confast.Web.Features.Gages.GageType", "GageType")
                        .WithMany("Gages")
                        .HasForeignKey("GageTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_gages_gage_types_gage_type_id");

                    b.Navigation("GageType");
                });

            modelBuilder.Entity("Confast.Web.Features.InspectionCriteria.InspectionCriteriaRevision", b =>
                {
                    b.HasOne("Confast.Web.Features.Parts.Part", "Part")
                        .WithMany("InspectionCriteriaRevisions")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_inspection_criteria_revisions_parts_part_id");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("Confast.Web.Features.InspectionCriteria.InspectionCriterion", b =>
                {
                    b.HasOne("Confast.Web.Features.Gages.GageType", "GageType")
                        .WithMany()
                        .HasForeignKey("GageTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_inspection_criteria_gage_types_gage_type_id");

                    b.HasOne("Confast.Web.Features.InspectionCriteria.InspectionCriteriaRevision", "Revision")
                        .WithMany("Criteria")
                        .HasForeignKey("InspectionCriteriaRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_inspection_criteria_revision_id");

                    b.Navigation("GageType");

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("Confast.Web.Features.InspectionCriteria.SecondaryProcessRequirement", b =>
                {
                    b.HasOne("Confast.Web.Features.InspectionCriteria.InspectionCriteriaRevision", "InspectionCriteriaRevision")
                        .WithMany("SecondaryProcessRequirements")
                        .HasForeignKey("InspectionCriteriaRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_secondary_process_requirements_revision_id");

                    b.HasOne("Confast.Web.Features.InspectionCriteria.SecondaryProcessType", "SecondaryProcessType")
                        .WithMany()
                        .HasForeignKey("SecondaryProcessTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_secondary_process_requirements_type_id");

                    b.Navigation("InspectionCriteriaRevision");

                    b.Navigation("SecondaryProcessType");
                });

            modelBuilder.Entity("Confast.Web.Features.Inspections.Inspection", b =>
                {
                    b.HasOne("Confast.Web.Features.Parts.Part", "Part")
                        .WithMany("Inspections")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_inspections_parts_part_id");

                    b.HasOne("Confast.Web.Features.InspectionCriteria.InspectionCriteriaRevision", "InspectionCriteriaRevision")
                        .WithMany("Inspections")
                        .HasForeignKey("InspectionCriteriaRevisionId", "PartId")
                        .HasPrincipalKey("Id", "PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_inspections_revision_id_part_id");

                    b.Navigation("InspectionCriteriaRevision");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("Confast.Web.Features.Inspections.InspectionResult", b =>
                {
                    b.HasOne("Confast.Web.Features.InspectionCriteria.InspectionCriterion", "InspectionCriterion")
                        .WithMany("InspectionResults")
                        .HasForeignKey("InspectionCriterionId", "InspectionCriteriaRevisionId")
                        .HasPrincipalKey("Id", "InspectionCriteriaRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_inspection_results_criterion_id_revision_id");

                    b.HasOne("Confast.Web.Features.Inspections.Inspection", "Inspection")
                        .WithMany("Results")
                        .HasForeignKey("InspectionId", "InspectionCriteriaRevisionId")
                        .HasPrincipalKey("Id", "InspectionCriteriaRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_inspection_results_inspection_id_revision_id");

                    b.Navigation("Inspection");

                    b.Navigation("InspectionCriterion");
                });

            modelBuilder.Entity("Confast.Web.Features.Parts.Part", b =>
                {
                    b.HasOne("Confast.Web.Features.Customers.Customer", "Customer")
                        .WithMany("Parts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_parts_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Confast.Web.Features.Customers.Customer", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("Confast.Web.Features.Gages.GageType", b =>
                {
                    b.Navigation("Gages");
                });

            modelBuilder.Entity("Confast.Web.Features.InspectionCriteria.InspectionCriteriaRevision", b =>
                {
                    b.Navigation("Criteria");

                    b.Navigation("Inspections");

                    b.Navigation("SecondaryProcessRequirements");
                });

            modelBuilder.Entity("Confast.Web.Features.InspectionCriteria.InspectionCriterion", b =>
                {
                    b.Navigation("InspectionResults");
                });

            modelBuilder.Entity("Confast.Web.Features.Inspections.Inspection", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("Confast.Web.Features.Parts.Part", b =>
                {
                    b.Navigation("InspectionCriteriaRevisions");

                    b.Navigation("Inspections");
                });
#pragma warning restore 612, 618
        }
    }
}
