// <auto-generated />
using System;
using Confast.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Confast.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260831195726_AddCertificationEmailImplicitCc")]
    partial class AddCertificationEmailImplicitCc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Confast.Web.Features.Customers.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Confast.Web.Features.Customers.Plant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AddressLine1")
                        .HasColumnType("text")
                        .HasColumnName("address_line_1");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text")
                        .HasColumnName("address_line_2");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PlantCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("plant_code");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("PK_plants");

                    b.HasIndex("CustomerId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_plants_customer_id_name");

                    b.ToTable("plants", null, t =>
                        {
                            t.HasCheckConstraint("CK_plants_certification_filename_override_not_blank", "certification_filename_pattern_override IS NULL OR btrim(certification_filename_pattern_override) <> ''");

                            t.HasCheckConstraint("CK_plants_name_not_blank", "btrim(name) <> ''");
                        });
                });

            modelBuilder.Entity("Confast.Web.Features.Customers.PlantCertificationRecipient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email_address");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long>("PlantId")
                        .HasColumnType("bigint")
                        .HasColumnName("plant_id");

                    b.Property<int>("RecipientType")
                        .HasColumnType("integer")
                        .HasColumnName("recipient_type");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("PK_plant_certification_recipients");

                    b.HasIndex("PlantId")
                        .HasDatabaseName("IX_plant_certification_recipients_plant_id");

                    b.ToTable("plant_certification_recipients", null, t =>
                        {
                            t.HasCheckConstraint("CK_plant_certification_recipients_email_not_blank", "btrim(email_address) <> ''");

                            t.HasCheckConstraint("CK_plant_certification_recipients_type", "recipient_type IN (1, 2)");
                        });
                });

            modelBuilder.Entity("Confast.Web.Features.Customers.PlantCertificationRequirement", b =>
                {
                    b.Property<long>("PlantId")
                        .HasColumnType("bigint")
                        .HasColumnName("plant_id");

                    b.Property<long>("CertificationTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("certification_type_id");

                    b.HasKey("PlantId", "CertificationTypeId")
                        .HasName("PK_plant_certification_requirements");

                    b.HasIndex("CertificationTypeId")
                        .HasDatabaseName("IX_plant_certification_requirements_type_id");

                    b.ToTable("plant_certification_requirements", (string)null);
                });

            modelBuilder.Entity("Confast.Web.Features.Customers.PlantCertificationSettings", b =>
                {
                    b.Property<long>("PlantId")
                        .HasColumnType("bigint")
                        .HasColumnName("plant_id");

                    b.Property<string>("FilenameTemplate")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("filename_template");

                    b.Property<string>("MultiPartFilenameTemplate")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("multi_part_filename_template");

                    b.Property<string>("SinglePartMultiLotFilenameTemplate")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("single_part_multi_lot_filename_template");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("PlantId")
                        .HasName("PK_plant_certification_settings");

                    b.ToTable("plant_certification_settings", null, t =>
                        {
                            t.HasCheckConstraint("CK_plant_certification_settings_filename_template_not_blank", "btrim(filename_template) <> ''");

                            t.HasCheckConstraint("CK_plant_certification_settings_multi_part_filename_not_blank", "btrim(multi_part_filename_template) <> ''");

                            t.HasCheckConstraint("CK_plant_certification_settings_single_part_multi_lot_filename_not_blank", "btrim(single_part_multi_lot_filename_template) <> ''");
                        });
                });

            modelBuilder.Entity("Confast.Web.Features.Gages.Gage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("GageNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gage_number");

                    b.Property<long>("GageTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("gage_type_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("PK_gages");

                    b.HasIndex("GageNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_gages_gage_number");

                    b.HasIndex("GageTypeId")
                        .HasDatabaseName("IX_gages_gage_type_id");

                    b.ToTable("gages", (string)null);
                });

            modelBuilder.Entity("Confast.Web.Features.Gages.GageType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("PK_gage_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_gage_types_name");

                    b.ToTable("gage_types", (string)null);
                });

            modelBuilder.Entity("Confast.Web.Features.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("job_title");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("UX_identity_users_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UX_identity_users_normalized_user_name");

                    b.ToTable("identity_users", (string)null);
                });

            modelBuilder.Entity("Confast.Web.Features.InspectionCriteria.CertificationType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK_certification_types");

                    b.HasIndex("DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("UX_certification_types_display_order");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_certification_types_name");

                    b.ToTable("certification_types", null, t =>
                        {
                            t.HasCheckConstraint("CK_certification_types_display_order", "display_order > 0");

                            t.HasCheckConstraint("CK_certification_types_name_not_blank", "btrim(name) <> ''");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DisplayOrder = 1,
                            Name = "CBP"
                        },
                        new
                        {
                            Id = 2L,
                            DisplayOrder = 2,
                            Name = "Clean"
                        },
                        new
                        {
                            Id = 3L,
                            DisplayOrder = 3,
                            Name = "C of C"
                        },
                        new
                        {
                            Id = 4L,
                            DisplayOrder = 4,
                            Name = "Gall"
                        },
                        new
                        {
                            Id = 5L,
                            DisplayOrder = 5,
                            Name = "Hardness"
                        },
                        new
                        {
                            Id = 6L,
                            DisplayOrder = 6,
                            Name = "Heat"
                        },
                        new
                        {
                            Id = 7L,
                            DisplayOrder = 7,
                            Name = "Material"
                        },
                        new
                        {
                            Id = 8L,
                            DisplayOrder = 8,
                            Name = "Patch"
                        },
                        new
                        {
                            Id = 9L,
                            DisplayOrder = 9,
                            Name = "Plate"
                        },
                        new
                        {
                            Id = 10L,
                            DisplayOrder = 10,
                            Name = "Salt Spray"
                        },
                        new
                        {
                            Id = 11L,
                            DisplayOrder = 11,
                            Name = "SPC"
                        },
                        new
                        {
                            Id = 12L,
                            DisplayOrder = 12,
                            Name = "Supplier Inspection"
                        },
                        new
                        {
                            Id = 13L,
                            DisplayOrder = 13,
                            Name = "Tensile/Proof Load/Yield"
                        },
                        new
                        {
                            Id = 14L,
                            DisplayOrder = 14,
                            Name = "Torque"
                        },
                        new
                        {
                            Id = 15L,
                            DisplayOrder = 15,
                            Name = "Notes/Misc"
                        });
                });

            modelBuilder.Entity("Confast.Web.Features.InspectionCriteria.InspectionCriteriaRevision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ChangeNote")
                        .HasColumnType("text")
                        .HasColumnName("change_note");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<byte[]>("MasterPrintContent")
                        .HasColumnType("bytea")
                        .HasColumnName("master_print_content");

                    b.Property<string>("MasterPrintFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("master_print_file_name");

                    b.Property<DateTimeOffset?>("MasterPrintUploadedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("master_print_uploaded_at_utc");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PartDescription")
                        .HasColumnType("text")
                        .HasColumnName("part_description");

                    b.Property<long>("PartId")
                        .HasColumnType("bigint")
                        .HasColumnName("part_id");

                    b.Property<string>("PrintRevisionNumber")
                        .HasColumnType("text")
                        .HasColumnName("print_revision_number");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("revision_number");

                    b.Property<string>("SpecificationUsed")
                        .HasColumnType("text")
                        .HasColumnName("specification_used");

                    b.Property<DateTimeOffset?>("SupersededAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("superseded_at_utc");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("PK_inspection_criteria_revisions");

                    b.HasAlternateKey("Id", "PartId")
                        .HasName("AK_inspection_criteria_revisions_id_part_id");

                    b.HasIndex("PartId", "RevisionNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_inspection_criteria_revisions_part_id_revision_number");

                    b.HasIndex(new[] { "PartId" }, "IX_inspection_criteria_revisions_current_guard")
                        .IsUnique()
                        .HasDatabaseName("UX_inspection_criteria_revisions_one_current_per_part")
                        .HasFilter("published_at_utc IS NOT NULL AND superseded_at_utc IS NULL");

                    b.HasIndex(new[] { "PartId" }, "IX_inspection_criteria_revisions_draft_guard")
                        .IsUnique()
                        .HasDatabaseName("UX_inspection_criteria_revisions_one_draft_per_part")
                        .HasFilter("published_at_utc IS NULL");

                    b.ToTable("inspection_criteria_revisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_inspection_criteria_revisions_revision_number", "revision_number > 0");

                            t.HasCheckConstraint("CK_inspection_criteria_revisions_superseded_after_published", "superseded_at_utc IS NULL OR published_at_utc IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Confast.Web.Features.InspectionCriteria.InspectionCriterion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<long?>("GageTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("gage_type_id");

                    b.Property<long>("InspectionCriteriaRevisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("inspection_criteria_revision_id");

                    b.Property<string>("InspectionMethod")
                        .HasColumnType("text")
                        .HasColumnName("inspection_method");

                    b.Property<int>("InspectionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("inspection_number");

                    b.Property<string>("MaximumOrTolerance")
                        .HasColumnType("text")
                        .HasColumnName("maximum_or_tolerance");

                    b.Property<string>("Minimum")
                        .HasColumnType("text")
                        .HasColumnName("minimum");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("PK_inspection_criteria");

                    b.HasAlternateKey("Id", "InspectionCriteriaRevisionId")
                        .HasName("AK_inspection_criteria_id_revision_id");

                    b.HasIndex("GageTypeId")
                        .HasDatabaseName("IX_inspection_criteria_gage_type_id");

                    b.HasIndex("InspectionCriteriaRevisionId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("UX_inspection_criteria_revision_id_display_order");

                    b.HasIndex("InspectionCriteriaRevisionId", "InspectionNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_inspection_criteria_revision_id_inspection_number");

                    b.ToTable("inspection_criteria", null, t =>
                        {
                            t.HasCheckConstraint("CK_inspection_criteria_display_order", "display_order > 0");

                            t.HasCheckConstraint("CK_inspection_criteria_inspection_number", "inspection_number > 0");
                        });
                });

            modelBuilder.Entity("Confast.Web.Features.InspectionCriteria.RevisionCertificationRequirement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CertificationTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("certification_type_id");

                    b.Property<string>("CertificationTypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("certification_type_name");

                    b.Property<long>("InspectionCriteriaRevisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("inspection_criteria_revision_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("RequirementLevel")
                        .HasColumnType("integer")
                        .HasColumnName("requirement_level");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("PK_revision_certification_requirements");

                    b.HasIndex("CertificationTypeId")
                        .HasDatabaseName("IX_revision_certification_requirements_type_id");

                    b.HasIndex("InspectionCriteriaRevisionId", "CertificationTypeId")
                        .IsUnique()
                        .HasDatabaseName("UX_revision_certification_requirements_revision_id_type_id");

                    b.ToTable("revision_certification_requirements", null, t =>
                        {
                            t.HasCheckConstraint("CK_revision_certification_requirements_level", "requirement_level IN (1, 2)");

                            t.HasCheckConstraint("CK_revision_certification_requirements_type_name_not_blank", "btrim(certification_type_name) <> ''");
                        });
                });

            modelBuilder.Entity("Confast.Web.Features.InspectionCriteria.SecondaryProcessRequirement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("InspectionCriteriaRevisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("inspection_criteria_revision_id");

                    b.Property<long>("SecondaryProcessTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("secondary_process_type_id");

                    b.Property<string>("Specification")
                        .HasColumnType("text")
                        .HasColumnName("specification");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("PK_secondary_process_requirements");

                    b.HasAlternateKey("Id", "InspectionCriteriaRevisionId")
                        .HasName("AK_secondary_process_requirements_id_revision_id");

                    b.HasIndex("InspectionCriteriaRevisionId")
                        .HasDatabaseName("IX_secondary_process_requirements_revision_id");

                    b.HasIndex("SecondaryProcessTypeId")
                        .HasDatabaseName("IX_secondary_process_requirements_type_id");

                    b.ToTable("secondary_process_requirements", (string)null);
                });

            modelBuilder.Entity("Confast.Web.Features.InspectionCriteria.SecondaryProcessType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK_secondary_process_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_secondary_process_types_name");

                    b.ToTable("secondary_process_types", null, t =>
                        {
                            t.HasCheckConstraint("CK_secondary_process_types_name_not_blank", "btrim(name) <> ''");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Heat Treat"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Clean"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Patch"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Plate"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Sort"
                        });
                });

            modelBuilder.Entity("Confast.Web.Features.Inspections.CertificationDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<long>("InspectionCertificationId")
                        .HasColumnType("bigint")
                        .HasColumnName("inspection_certification_id");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<byte[]>("PreviewContent")
                        .HasColumnType("bytea")
                        .HasColumnName("preview_content");

                    b.Property<DateTimeOffset>("UploadedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("PK_certification_documents");

                    b.HasIndex("InspectionCertificationId")
                        .HasDatabaseName("IX_certification_documents_certification_id");

                    b.ToTable("certification_documents", (string)null);
                });

            modelBuilder.Entity("Confast.Web.Features.Inspections.CertificationEmailSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("ImplicitCcAddress")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("implicit_cc_address");

                    b.HasKey("Id")
                        .HasName("PK_certification_email_settings");

                    b.ToTable("certification_email_settings", null, t =>
                        {
                            t.HasCheckConstraint("CK_certification_email_settings_implicit_cc_not_blank", "implicit_cc_address IS NULL OR btrim(implicit_cc_address) <> ''");

                            t.HasCheckConstraint("CK_certification_email_settings_singleton", "id = 1");
                        });
                });

            modelBuilder.Entity("Confast.Web.Features.Inspections.CertificationEmailTemplate", b =>
                {
                    b.Property<int>("TemplateType")
                        .HasColumnType("integer")
                        .HasColumnName("template_type");

                    b.Property<string>("HtmlBodyTemplate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("html_body_template");

                    b.Property<string>("SubjectTemplate")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("subject_template");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("TemplateType")
                        .HasName("PK_certification_email_templates");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("certification_email_templates", null, t =>
                        {
                            t.HasCheckConstraint("CK_certification_email_templates_body_not_blank", "btrim(html_body_template) <> ''");

                            t.HasCheckConstraint("CK_certification_email_templates_subject_not_blank", "btrim(subject_template) <> ''");
                        });
                });

            modelBuilder.Entity("Confast.Web.Features.Inspections.Inspection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConformancePoNumber")
                        .HasColumnType("text")
                        .HasColumnName("conformance_po_number");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly?>("DateReceived")
                        .HasColumnType("date")
                        .HasColumnName("date_received");

                    b.Property<string>("InHouseNotes")
                        .HasColumnType("text")
                        .HasColumnName("in_house_notes");

                    b.Property<long>("InspectionCriteriaRevisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("inspection_criteria_revision_id");

                    b.Property<DateOnly>("InspectionDate")
                        .HasColumnType("date")
                        .HasColumnName("inspection_date");

                    b.Property<string>("Inspector")
                        .HasColumnType("text")
                        .HasColumnName("inspector");

                    b.Property<string>("InspectorNotes")
                        .HasColumnType("text")
                        .HasColumnName("inspector_notes");

                    b.Property<string>("LotNumber")
                        .HasColumnType("text")
                        .HasColumnName("lot_number");

                    b.Property<string>("ManufacturerLotNumber")
                        .HasColumnType("text")
                        .HasColumnName("manufacturer_lot_number");

                    b.Property<long>("PartId")
                        .HasColumnType("bigint")
                        .HasColumnName("part_id");

                    b.Property<int?>("QuantityInspected")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_inspected");

                    b.Property<int?>("QuantityReceived")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_received");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("PK_inspections");

                    b.HasAlternateKey("Id", "InspectionCriteriaRevisionId")
                        .HasName("AK_inspections_id_revision_id");

                    b.HasIndex("InspectionCriteriaRevisionId")
                        .HasDatabaseName("IX_inspections_revision_id");

                    b.HasIndex("InspectionDate")
                        .HasDatabaseName("IX_inspections_inspection_date");

                    b.HasIndex("PartId")
                        .HasDatabaseName("IX_inspections_part_id");

                    b.HasIndex("InspectionCriteriaRevisionId", "PartId");

                    b.ToTable("inspections", null, t =>
                        {
                            t.HasCheckConstraint("CK_inspections_quantity_inspected", "quantity_inspected IS NULL OR quantity_inspected > 0");

                            t.HasCheckConstraint("CK_inspections_quantity_received", "quantity_received IS NULL OR quantity_received > 0");
                        });
                });

            modelBuilder.Entity("Confast.Web.Features.Inspections.InspectionCertification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CertificationTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("certification_type_id");

                    b.Property<string>("CertificationTypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("certification_type_name");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("InspectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("inspection_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("PK_inspection_certifications");

                    b.HasIndex("CertificationTypeId")
                        .HasDatabaseName("IX_inspection_certifications_type_id");

                    b.HasIndex("InspectionId", "CertificationTypeId")
                        .IsUnique()
                        .HasDatabaseName("UX_inspection_certifications_inspection_id_type_id");

                    b.ToTable("inspection_certifications", null, t =>
                        {
                            t.HasCheckConstraint("CK_inspection_certifications_type_name_not_blank", "btrim(certification_type_name) <> ''");
                        });
                });

            modelBuilder.Entity("Confast.Web.Features.Inspections.InspectionCertificationRequirement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CertificationTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("certification_type_id");

                    b.Property<string>("CertificationTypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("certification_type_name");

                    b.Property<long>("InspectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("inspection_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("RequirementLevel")
                        .HasColumnType("integer")
                        .HasColumnName("requirement_level");

                    b.HasKey("Id")
                        .HasName("PK_inspection_certification_requirements");

                    b.HasIndex("CertificationTypeId")
                        .HasDatabaseName("IX_inspection_certification_requirements_type_id");

                    b.HasIndex("InspectionId", "CertificationTypeId")
                        .IsUnique()
                        .HasDatabaseName("UX_inspection_certification_requirements_inspection_id_type_id");

                    b.ToTable("inspection_certification_requirements", null, t =>
                        {
                            t.HasCheckConstraint("CK_inspection_certification_requirements_level", "requirement_level IN (1, 2)");

                            t.HasCheckConstraint("CK_inspection_certification_requirements_type_name_not_blank", "btrim(certification_type_name) <> ''");
                        });
                });

            modelBuilder.Entity("Confast.Web.Features.Inspections.InspectionResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActualMax")
                        .HasColumnType("text")
                        .HasColumnName("actual_max");

                    b.Property<string>("ActualMin")
                        .HasColumnType("text")
                        .HasColumnName("actual_min");

                    b.Property<long?>("GageId")
                        .HasColumnType("bigint")
                        .HasColumnName("gage_id");

                    b.Property<string>("GageNumber")
                        .HasColumnType("text")
                        .HasColumnName("gage_number");

                    b.Property<long>("InspectionCriteriaRevisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("inspection_criteria_revision_id");

                    b.Property<long>("InspectionCriterionId")
                        .HasColumnType("bigint")
                        .HasColumnName("inspection_criterion_id");

                    b.Property<long>("InspectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("inspection_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("PK_inspection_results");

                    b.HasIndex("GageId")
                        .HasDatabaseName("IX_inspection_results_gage_id");

                    b.HasIndex("InspectionCriterionId", "InspectionCriteriaRevisionId")
                        .HasDatabaseName("IX_inspection_results_criterion_id_revision_id");

                    b.HasIndex("InspectionId", "InspectionCriteriaRevisionId");

                    b.HasIndex("InspectionId", "InspectionCriterionId")
                        .IsUnique()
                        .HasDatabaseName("UX_inspection_results_inspection_id_criterion_id");

                    b.ToTable("inspection_results", (string)null);
                });

            modelBuilder.Entity("Confast.Web.Features.Inspections.InspectionSecondaryProcess", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("InspectionCriteriaRevisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("inspection_criteria_revision_id");

                    b.Property<long>("InspectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("inspection_id");

                    b.Property<bool>("IsComplete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_complete");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("process_name");

                    b.Property<string>("PurchaseOrderNumber")
                        .HasColumnType("text")
                        .HasColumnName("purchase_order_number");

                    b.Property<long>("SecondaryProcessRequirementId")
                        .HasColumnType("bigint")
                        .HasColumnName("secondary_process_requirement_id");

                    b.Property<string>("Specification")
                        .HasColumnType("text")
                        .HasColumnName("specification");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("PK_inspection_secondary_processes");

                    b.HasIndex("InspectionId", "InspectionCriteriaRevisionId");

                    b.HasIndex("InspectionId", "SecondaryProcessRequirementId")
                        .IsUnique()
                        .HasDatabaseName("UX_inspection_secondary_processes_inspection_id_requirement_id");

                    b.HasIndex("SecondaryProcessRequirementId", "InspectionCriteriaRevisionId")
                        .HasDatabaseName("IX_inspection_secondary_processes_requirement_id_revision_id");

                    b.ToTable("inspection_secondary_processes", null, t =>
                        {
                            t.HasCheckConstraint("CK_inspection_secondary_processes_process_name_not_blank", "btrim(process_name) <> ''");
                        });
                });

            modelBuilder.Entity("Confast.Web.Features.Parts.Part", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("part_number");

                    b.Property<string>("Revision")
                        .HasColumnType("text")
                        .HasColumnName("revision");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("PK_parts");

                    b.HasIndex("CustomerId", "PartNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_parts_customer_id_part_number");

                    b.ToTable("parts", (string)null);
                });

            modelBuilder.Entity("Confast.Web.Features.Parts.PartPlant", b =>
                {
                    b.Property<long>("PartId")
                        .HasColumnType("bigint")
                        .HasColumnName("part_id");

                    b.Property<long>("PlantId")
                        .HasColumnType("bigint")
                        .HasColumnName("plant_id");

                    b.HasKey("PartId", "PlantId")
                        .HasName("PK_part_plants");

                    b.HasIndex("PlantId")
                        .HasDatabaseName("IX_part_plants_plant_id");

                    b.ToTable("part_plants", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("UX_identity_roles_normalized_name");

                    b.ToTable("identity_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "47cd3d4a-0d66-4acf-8556-4017336798d8",
                            ConcurrencyStamp = "47cd3d4a-0d66-4acf-8556-4017336798d8",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "9eb9ef78-7737-47a5-89fc-10513d3e9c1b",
                            ConcurrencyStamp = "9eb9ef78-7737-47a5-89fc-10513d3e9c1b",
                            Name = "Quality",
                            NormalizedName = "QUALITY"
                        },
                        new
                        {
                            Id = "56b3fc07-e152-42ca-b074-a823900c93b3",
                            ConcurrencyStamp = "56b3fc07-e152-42ca-b074-a823900c93b3",
                            Name = "Production",
                            NormalizedName = "PRODUCTION"
                        },
                        new
                        {
                            Id = "1b171cb9-9273-42fc-b790-ea934dbb12b9",
                            ConcurrencyStamp = "1b171cb9-9273-42fc-b790-ea934dbb12b9",
                            Name = "ReadOnly",
                            NormalizedName = "READONLY"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_identity_role_claims_role_id");

                    b.ToTable("identity_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_identity_user_claims_user_id");

                    b.ToTable("identity_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_identity_user_logins_user_id");

                    b.ToTable("identity_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_identity_user_roles_role_id");

                    b.ToTable("identity_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("identity_user_tokens", (string)null);
                });

            modelBuilder.Entity("Confast.Web.Features.Customers.Plant", b =>
                {
                    b.HasOne("Confast.Web.Features.Customers.Customer", "Customer")
                        .WithMany("Plants")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_plants_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Confast.Web.Features.Customers.PlantCertificationRecipient", b =>
                {
                    b.HasOne("Confast.Web.Features.Customers.Plant", "Plant")
                        .WithMany("CertificationRecipients")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_plant_certification_recipients_plant_id");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Confast.Web.Features.Customers.PlantCertificationRequirement", b =>
                {
                    b.HasOne("Confast.Web.Features.InspectionCriteria.CertificationType", "CertificationType")
                        .WithMany()
                        .HasForeignKey("CertificationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_plant_certification_requirements_type_id");

                    b.HasOne("Confast.Web.Features.Customers.Plant", "Plant")
                        .WithMany("CertificationRequirements")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_plant_certification_requirements_plant_id");

                    b.Navigation("CertificationType");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Confast.Web.Features.Customers.PlantCertificationSettings", b =>
                {
                    b.HasOne("Confast.Web.Features.Customers.Plant", "Plant")
                        .WithOne("CertificationSettings")
                        .HasForeignKey("Confast.Web.Features.Customers.PlantCertificationSettings", "PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_plant_certification_settings_plant_id");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Confast.Web.Features.Gages.Gage", b =>
                {
                    b.HasOne("Confast.Web.Features.Gages.GageType", "GageType")
                        .WithMany("Gages")
                        .HasForeignKey("GageTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_gages_gage_types_gage_type_id");

                    b.Navigation("GageType");
                });

            modelBuilder.Entity("Confast.Web.Features.InspectionCriteria.InspectionCriteriaRevision", b =>
                {
                    b.HasOne("Confast.Web.Features.Parts.Part", "Part")
                        .WithMany("InspectionCriteriaRevisions")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_inspection_criteria_revisions_parts_part_id");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("Confast.Web.Features.InspectionCriteria.InspectionCriterion", b =>
                {
                    b.HasOne("Confast.Web.Features.Gages.GageType", "GageType")
                        .WithMany()
                        .HasForeignKey("GageTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_inspection_criteria_gage_types_gage_type_id");

                    b.HasOne("Confast.Web.Features.InspectionCriteria.InspectionCriteriaRevision", "Revision")
                        .WithMany("Criteria")
                        .HasForeignKey("InspectionCriteriaRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_inspection_criteria_revision_id");

                    b.Navigation("GageType");

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("Confast.Web.Features.InspectionCriteria.RevisionCertificationRequirement", b =>
                {
                    b.HasOne("Confast.Web.Features.InspectionCriteria.CertificationType", "CertificationType")
                        .WithMany()
                        .HasForeignKey("CertificationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_revision_certification_requirements_type_id");

                    b.HasOne("Confast.Web.Features.InspectionCriteria.InspectionCriteriaRevision", "InspectionCriteriaRevision")
                        .WithMany("CertificationRequirements")
                        .HasForeignKey("InspectionCriteriaRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_revision_certification_requirements_revision_id");

                    b.Navigation("CertificationType");

                    b.Navigation("InspectionCriteriaRevision");
                });

            modelBuilder.Entity("Confast.Web.Features.InspectionCriteria.SecondaryProcessRequirement", b =>
                {
                    b.HasOne("Confast.Web.Features.InspectionCriteria.InspectionCriteriaRevision", "InspectionCriteriaRevision")
                        .WithMany("SecondaryProcessRequirements")
                        .HasForeignKey("InspectionCriteriaRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_secondary_process_requirements_revision_id");

                    b.HasOne("Confast.Web.Features.InspectionCriteria.SecondaryProcessType", "SecondaryProcessType")
                        .WithMany()
                        .HasForeignKey("SecondaryProcessTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_secondary_process_requirements_type_id");

                    b.Navigation("InspectionCriteriaRevision");

                    b.Navigation("SecondaryProcessType");
                });

            modelBuilder.Entity("Confast.Web.Features.Inspections.CertificationDocument", b =>
                {
                    b.HasOne("Confast.Web.Features.Inspections.InspectionCertification", "InspectionCertification")
                        .WithMany("Documents")
                        .HasForeignKey("InspectionCertificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_certification_documents_certification_id");

                    b.Navigation("InspectionCertification");
                });

            modelBuilder.Entity("Confast.Web.Features.Inspections.CertificationEmailTemplate", b =>
                {
                    b.HasOne("Confast.Web.Features.Identity.ApplicationUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_certification_email_templates_updated_by_user_id");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Confast.Web.Features.Inspections.Inspection", b =>
                {
                    b.HasOne("Confast.Web.Features.Parts.Part", "Part")
                        .WithMany("Inspections")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_inspections_parts_part_id");

                    b.HasOne("Confast.Web.Features.InspectionCriteria.InspectionCriteriaRevision", "InspectionCriteriaRevision")
                        .WithMany("Inspections")
                        .HasForeignKey("InspectionCriteriaRevisionId", "PartId")
                        .HasPrincipalKey("Id", "PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_inspections_revision_id_part_id");

                    b.Navigation("InspectionCriteriaRevision");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("Confast.Web.Features.Inspections.InspectionCertification", b =>
                {
                    b.HasOne("Confast.Web.Features.InspectionCriteria.CertificationType", "CertificationType")
                        .WithMany()
                        .HasForeignKey("CertificationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_inspection_certifications_type_id");

                    b.HasOne("Confast.Web.Features.Inspections.Inspection", "Inspection")
                        .WithMany("Certifications")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_inspection_certifications_inspection_id");

                    b.Navigation("CertificationType");

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("Confast.Web.Features.Inspections.InspectionCertificationRequirement", b =>
                {
                    b.HasOne("Confast.Web.Features.InspectionCriteria.CertificationType", "CertificationType")
                        .WithMany()
                        .HasForeignKey("CertificationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_inspection_certification_requirements_type_id");

                    b.HasOne("Confast.Web.Features.Inspections.Inspection", "Inspection")
                        .WithMany("CertificationRequirements")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_inspection_certification_requirements_inspection_id");

                    b.Navigation("CertificationType");

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("Confast.Web.Features.Inspections.InspectionResult", b =>
                {
                    b.HasOne("Confast.Web.Features.Gages.Gage", "Gage")
                        .WithMany()
                        .HasForeignKey("GageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_inspection_results_gages_gage_id");

                    b.HasOne("Confast.Web.Features.InspectionCriteria.InspectionCriterion", "InspectionCriterion")
                        .WithMany("InspectionResults")
                        .HasForeignKey("InspectionCriterionId", "InspectionCriteriaRevisionId")
                        .HasPrincipalKey("Id", "InspectionCriteriaRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_inspection_results_criterion_id_revision_id");

                    b.HasOne("Confast.Web.Features.Inspections.Inspection", "Inspection")
                        .WithMany("Results")
                        .HasForeignKey("InspectionId", "InspectionCriteriaRevisionId")
                        .HasPrincipalKey("Id", "InspectionCriteriaRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_inspection_results_inspection_id_revision_id");

                    b.Navigation("Gage");

                    b.Navigation("Inspection");

                    b.Navigation("InspectionCriterion");
                });

            modelBuilder.Entity("Confast.Web.Features.Inspections.InspectionSecondaryProcess", b =>
                {
                    b.HasOne("Confast.Web.Features.Inspections.Inspection", "Inspection")
                        .WithMany("SecondaryProcesses")
                        .HasForeignKey("InspectionId", "InspectionCriteriaRevisionId")
                        .HasPrincipalKey("Id", "InspectionCriteriaRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_inspection_secondary_processes_inspection_id_revision_id");

                    b.HasOne("Confast.Web.Features.InspectionCriteria.SecondaryProcessRequirement", "SecondaryProcessRequirement")
                        .WithMany("InspectionSecondaryProcesses")
                        .HasForeignKey("SecondaryProcessRequirementId", "InspectionCriteriaRevisionId")
                        .HasPrincipalKey("Id", "InspectionCriteriaRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_inspection_secondary_processes_requirement_id_revision_id");

                    b.Navigation("Inspection");

                    b.Navigation("SecondaryProcessRequirement");
                });

            modelBuilder.Entity("Confast.Web.Features.Parts.Part", b =>
                {
                    b.HasOne("Confast.Web.Features.Customers.Customer", "Customer")
                        .WithMany("Parts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_parts_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Confast.Web.Features.Parts.PartPlant", b =>
                {
                    b.HasOne("Confast.Web.Features.Parts.Part", "Part")
                        .WithMany("PartPlants")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_part_plants_parts_part_id");

                    b.HasOne("Confast.Web.Features.Customers.Plant", "Plant")
                        .WithMany("PartPlants")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_part_plants_plants_plant_id");

                    b.Navigation("Part");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Confast.Web.Features.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Confast.Web.Features.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Confast.Web.Features.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Confast.Web.Features.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Confast.Web.Features.Customers.Customer", b =>
                {
                    b.Navigation("Parts");

                    b.Navigation("Plants");
                });

            modelBuilder.Entity("Confast.Web.Features.Customers.Plant", b =>
                {
                    b.Navigation("CertificationRecipients");

                    b.Navigation("CertificationRequirements");

                    b.Navigation("CertificationSettings");

                    b.Navigation("PartPlants");
                });

            modelBuilder.Entity("Confast.Web.Features.Gages.GageType", b =>
                {
                    b.Navigation("Gages");
                });

            modelBuilder.Entity("Confast.Web.Features.InspectionCriteria.InspectionCriteriaRevision", b =>
                {
                    b.Navigation("CertificationRequirements");

                    b.Navigation("Criteria");

                    b.Navigation("Inspections");

                    b.Navigation("SecondaryProcessRequirements");
                });

            modelBuilder.Entity("Confast.Web.Features.InspectionCriteria.InspectionCriterion", b =>
                {
                    b.Navigation("InspectionResults");
                });

            modelBuilder.Entity("Confast.Web.Features.InspectionCriteria.SecondaryProcessRequirement", b =>
                {
                    b.Navigation("InspectionSecondaryProcesses");
                });

            modelBuilder.Entity("Confast.Web.Features.Inspections.Inspection", b =>
                {
                    b.Navigation("CertificationRequirements");

                    b.Navigation("Certifications");

                    b.Navigation("Results");

                    b.Navigation("SecondaryProcesses");
                });

            modelBuilder.Entity("Confast.Web.Features.Inspections.InspectionCertification", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Confast.Web.Features.Parts.Part", b =>
                {
                    b.Navigation("InspectionCriteriaRevisions");

                    b.Navigation("Inspections");

                    b.Navigation("PartPlants");
                });
#pragma warning restore 612, 618
        }
    }
}
