using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Confast.Web.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddInspectionLineageHistory : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE lot_flips ADD COLUMN IF NOT EXISTS quantity_moved integer;

                CREATE TABLE IF NOT EXISTS lot_duplications (
                    id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_lot_duplications" PRIMARY KEY,
                    source_inspection_id bigint NOT NULL CONSTRAINT "FK_lot_duplications_source_inspection_id" REFERENCES inspections (id) ON DELETE RESTRICT,
                    destination_inspection_id bigint NOT NULL CONSTRAINT "FK_lot_duplications_destination_inspection_id" REFERENCES inspections (id) ON DELETE RESTRICT,
                    quantity_moved integer NOT NULL,
                    performed_at_utc timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT "CK_lot_duplications_different_inspections" CHECK (source_inspection_id <> destination_inspection_id),
                    CONSTRAINT "CK_lot_duplications_positive_quantity" CHECK (quantity_moved > 0)
                );

                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'CK_lot_flips_positive_quantity') THEN
                        ALTER TABLE lot_flips ADD CONSTRAINT "CK_lot_flips_positive_quantity"
                            CHECK (quantity_moved IS NULL OR quantity_moved > 0);
                    END IF;
                END $$;

                CREATE INDEX IF NOT EXISTS "IX_lot_duplications_source_inspection_id" ON lot_duplications (source_inspection_id);
                CREATE UNIQUE INDEX IF NOT EXISTS "UX_lot_duplications_destination_inspection_id" ON lot_duplications (destination_inspection_id);
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS lot_duplications;
                ALTER TABLE lot_flips DROP CONSTRAINT IF EXISTS "CK_lot_flips_positive_quantity";
                ALTER TABLE lot_flips DROP COLUMN IF EXISTS quantity_moved;
                """);
        }
    }
}
